### ISSUE TITLE
Can't watch Afreeca streams that use hls

### ISSUE THREAD

**Issue by xRaiken** [chrippa/livestreamer#1104]
Hello I ran into the problem that I can't watch afreeca stream with hls, rtmp works fine.

The error message i get is:
[cli][info] Found matching plugin afreeca for URL afreeca.com/********
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Could not open stream: Unable to open URL: 
http://chromecast.afreeca.gscdn.com/livestream-10/auth_playlist.m3u8 (400 Client Error: Bad Request)

Thanks for any kind of tip.

**Comment by 0880** [comment]
If you get this error message, then you are probably using an outdated version (#982).

**Comment by xRaiken** [comment]
@0880 I downloaded the 1.12.2 via this link: http://docs.livestreamer.io/install.html

Using the windows binaries installer.

Did I do something wrong? Should I  use the zip file?

**Comment by 0880** [comment]
http://livestreamer-builds.s3.amazonaws.com/livestreamer-latest-win32.zip

**Comment by xRaiken** [comment]
@0880 This seemed to work! Thanks a lot.

Is there any other way to start a stream other than typing the whole path into cmd? With the installer i just had to type "livestreamer". Any way I can do this with the zip version?

**Comment by 0880** [comment]
>Is there any other way to start a stream other than typing the whole path into cmd? With the installer i just had to type "livestreamer".

Simply add the Livestreamer directory to your [path variable] (https://en.wikipedia.org/wiki/PATH_(variable)).

Advanced System Settings (System Properties) - Environment Variables - Path

Or edit the path value in the registry.

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment

**Comment by xRaiken** [comment]
@0880 Thank you so so much! It's working perfectly now. Thanks!

**Comment by tenminute** [comment]
@xRaiken @0880 

How exactly do you use the Nightly/latest build? I've used livestreamer for a little while now for Afreeca, but I'm still a total beginner to all of this and how it works. I've only installed it with the windows installer and got it to work for one channel (it's an rtmp stream, and other rtmp streams work) (as long as it worked I didn't bother messing with it more, but there are some hls streams I really want to watch now). I uninstalled it and download the Nightly build as @0880 suggested but I don't know how to use it. Tried reading some of the tutorials but it seems so confusing. Doesn't really tell you how to use/launch livestreamer without the "installer" download. I just want to know what the hell I do and where to put things when I download the Nightly build. Please help! I'd really appreciate it! Thanks!

**Comment by skulblakka** [comment]
@tenminute Just download the ZIP and extract it somewhere. [Now add the new location to the path variable.](https://www.java.com/en/download/help/path.xml) Make sure that the path you add actually contain the livestreamer.exe

After this you can use livestreamer like with the installer version. (you might have to relog or reboot to make the changes take affect)

**Comment by tenminute** [comment]
@skulblakka Ok... so I downloaded the Nightly build ZIP, extracted that to my desktop and got a folder named "livestreamer-v1.12.2-77-g8dd6a69", renamed it to "Livestreamer", copy/pasted it into "C:\Program Files (x86)" folder to get "C:\Program Files (x86)\Livestreamer"...... edited the PATH to "C:\Program Files (x86)\Livestreamer" (without quotation marks) like in the link you gave me... but still not working??? Am I doing something wrong???

This is what I get when I try rtmp streams...
[cli][info] Opening stream: live (rtmp)
[cli][error] Could not open stream: Unable to find C:\Program Files (x86)\Livestreamer\rtmpdump\rtmpdump.exe command

When I try hls streams, it starts VLC like it's working, shows Afreeca's countdown thingy and then when it gets to 0 it just doesn't do anything after that.

What I ORIGINALLY tried doing WHILE I had the "installer" installed, was download the Night build ZIP, extracted that "livestreamer-v1.12.2-77-g8dd6a69" folder, copied everything in there, and just pasted it in the "Livestreamer" folder created by the "installer" overwriting the files. Should that have worked? I didn't do anything with the PATH that time because I didn't know anything about that. BUT... rtmp streams were still working and hls streams were still doing that countdown thing and then not doing anything after reaching 0. And yeah, BEFORE I did any of this, I was just getting the error @xRaiken originally posted.

Sorry so long...

**Comment by skulblakka** [comment]
>Unable to find C:\Program Files (x86)\Livestreamer\rtmpdump\rtmpdump.exe command

You need rtmpdump to watch rtmp streams. You can download it [here](http://rtmpdump.mplayerhq.hu/). Just put the rtmpdump.exe inside C:\Program Files (x86)\Livestreamer\rtmpdump\ or change the path in the livestreamer configuration file.

**Comment by tenminute** [comment]
Sweet! Got it working! I guess hls streams wanted to magically start working too when it wasn't before. Awesome! Big thanks!
