### ISSUE TITLE
vaughnlive: unable to validate response text

### ISSUE THREAD

**Issue by c769214** [chrippa/livestreamer#1434]
livestreamer http://vaughnlive.tv/newzviewz best
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/newzviewz
error: Unable to validate response text: Minimum length is 3 but value is 1

BTW, the .py file is using this one : 
https://github.com/intact/livestreamer/blob/3cba09f0c286bf7d6a04333733661a96a29313c0/src/livestreamer/plugins/vaughnlive.py

**Comment by Miyabro** [comment]
I am also experiencing this issue.
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/wgg100
error: Unable to validate response text: Minimum length is 3 but value is 1

**Comment by intact** [comment]
@c769214 @Miyabro try updated version #1376

**Comment by Miyabro** [comment]
@intact Thank you, that worked perfectly.

**Comment by c769214** [comment]
@intact Thanks... this seems working

But I have one issue, 
the vaughnlive link is ok (few choppy) when viewing in the browser. 
But very choppy (and sometimes stopped) when using livestreamer command (even --file-caching and --network-caching command used in the VLC) 

livestreamer  -p "vlc --file-caching=8000 --network-caching=8000 " "http://vaughnlive.tv/sherming6666" best

any ideas?

**Comment by techmouse** [comment]
I'm just curious, is vaughnlive trying to break livestreamer or are they making a lot of changes to their site all the time now?

**Comment by fadster** [comment]
@intact Thanks a lot! :)

@techmouse Good question.

**Comment by fadster** [comment]
@intact Thanks a lot! :)

@techmouse Good question. Some of the changes seem legitimate, but rotating the "mvn" characters appears to be a very weak attempt to break third-party players.

**Comment by fadster** [comment]
@intact Thanks a lot! :)

@techmouse Good question. Some of the changes seem legitimate (eg. adding a server), but rotating the "mvn" characters appears to be a very weak attempt to break third-party players.

**Comment by fragtion** [comment]
@fadster: yup, my thoughts exactly - the rotating of mvn characters seems to answer the question about 3rd party players and intentionally throwing us off.  I suspect they were really doing this to alleviate excessive load on their servers (prioritizing those users who use the website/the flash player), but hopefully the addition of more 'load balancing' servers as part of the legitimate changes now means that they won't need to break 3rd party streaming anymore, because the cat-and-mouse chase is pretty lame. Whether we watch the streaming using VLC (preferred) or through a web browser (inconvenient), we're still ultimately going to watch the stream meaning that the bandwidth utilization on their servers will ultimately be the same so they aren't really achieving much by causing these disruptions except really pissing the viewers off

**Comment by Vinizavr** [comment]
Hello! Need help. I change mvn to vnm in vaughnlive.py but it still gives an error: 
error: Unable to validate response text: Minimum length is 3 but value is 1
Below is my version of the script, which worked fine until today:
https://github.com/Vinizavr/vaughnlive/blob/master/vaughnlive.py

P.S: Sorry from my bad english
