### ISSUE TITLE
How do I get a token and does it cost anything?

### ISSUE THREAD

**Issue by gaveitatry02** [chrippa/livestreamer#1672]
I really don't know how I got LiveStreamer to work.  It was over a year ago, and I just did some quick searches online and used trial and error.  I was even able to find a free token.  And somehow I set it all correctly.  And then I just type something like the following in Command Prompt:
livestreamer --http-header Client-ID=(some long number) twitch.tv/(twitch streamer name) audio_only

But now it doesn't work all of the time.  For instance, I'm getting this now:
[cli][info] Found matching plugin twitch for URL twitch.tv/(twitch streamer name)
error: Unable to open URL: https://api.twitch.tv/api/channels/ (twitch streamer name)/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)

It will probably work again later, but I have no idea what is causing this error message.  I'm thinking that maybe someone found the same token I did and maybe they are using it now which is keeping me from using it because maybe two people can't use it at the same time?  If that is the case, how do I get my own token and does it cost anything?

**Comment by skulblakka** [comment]
To answer your question: The client-id tokens are obtained by registering a application with Twitch.  As far as I know these don't cost anything. The tokens are used to identify a application with the Twitch-API and thus are supposed to be shared by everyone who is using the same application (meaning the issue is not related to others using an identical token).

The actual issue is not related to the client-id at all. The problem is that this project has not been updated for several year and the old TLS version used by Livestreamer is no longer supported by Twitch. While it is probably possible to update livestreamer I would recommend using [streamlink](https://github.com/streamlink/streamlink) which is a continuation of this project. (you wouldn't even have to use the `--http-header-client-ID` workaround anymore)

**Comment by gaveitatry02** [comment]
Thank you for referencing me to streamlink.  I'll have a look at it.  Does it let me play audio_only or some quality of video in my VLC player?

**Comment by skulblakka** [comment]
Like I said: streamlink is a continuation of livestreamer after it became obvious that livestreamer was abandoned. It can more or less do everything livestreamer can do.

**Comment by gaveitatry02** [comment]
Thanks skulb.  I made the switch today, and it is working.
