### ISSUE TITLE
PotPlayer won't play twitch.tv streams.

### ISSUE THREAD

**Issue by ppapadatis** [chrippa/livestreamer#280]
PotPlayer (64bit) is being passed to livestreamer via the --player argument, the player then opens but there is no output of the stream. PotPlayer just hangs there open doing nothing. The [cli][info] outputs "Found matching plugin [...] Opening stream [...] Starting player: [...]", then PotPlayer opens and then nothing.

**Comment by Fironet** [comment]
> --player-passthrough hls seems to work. don't know if something else works, but this one does for the moment

Thank you! I'd rather use the Mini64.exe version as all my settings exist in that version.

**Comment by githugt** [comment]
I'm pretty certain all the settings are passed between the live version and the Mini version. (Atleast all that I work with, do). Although don't quote me, but I think the settings are passed via the settings.ini file which is why (probably) changes in one means changes in other too.

**Comment by Fironet** [comment]
Mmm, all the settings are written to the ini file in my directory too but the live version ignores them for some reason. It also seems prone to freezing. Either way glad livestreamer is configured correctly. Works a treat.

**Comment by githugt** [comment]
Try installing it again, coz Live version isn't giving me any such issues. Another thing you can try is, instead of downloading the normal English version, try downloading the Korean version (You can change the language of it easily.) You'll also probably appreciate the bevy of additional features that does not exist in the Normal English version. :)
