### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by RudyBojangles** [chrippa/livestreamer#544]
Upon starting livestreamer, it hangs and gives me the following error:

error: Unable to open URL: https://api.twitch.tv/api/channels/***/access_token.json (HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /api/channels/***/access_token.json?as3=t (Caused by <class 'socket.error'>: [Errno 10054] An existing connection was forcibly closed by the remote host))

**Comment by wozeck1** [comment]
Hi

I am having this issue too. Even if I recheck for streams every 900 seconds (15mins) eventually after around 2 hours I will get a notice that "An existing connection was forcibly closed by the remote host". 

This doesn't make much sense given that I am checking for streams so infrequently I am surprised if I was sending too many requests.

However, I am more interested in a workaround, how did you accomplish this @Avbrella  ?

I have a batch file that runs:

```:start
livestreamer %url% best -o "filename - %date:/=-% %time::=-%.ts" --retry-streams 900 
```goto start

However, when when the error is thrown it does not go back to start it just hangs at the error.
If I close the terminal and rerun the file it starts to check for streams again so I am not temporarily banned I just need a way to catch this error and restart the process.

Hope that makes sense and I hope you can help

**Comment by SubNoizey** [comment]
Okay this is really weird, If I use the windows binaries on my windows 10 PC I get the following error.

C:\Program Files (x86)\Livestreamer>livestreamer --loglevel debug twitch.tv/esl_csgo best
[cli][info] Found matching plugin twitch for URL twitch.tv/esl_csgo
error: Unable to open URL: https://api.twitch.tv/api/channels/esl_csgo/access_token.json (HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /api/channels/esl_csgo/access_token.json?as3=t (Caused by <class 'socket.error'>: [Errno 10054] An existing connection was forcibly closed by the remote host))


But I installed it via PIP and it works.


[cli][info] Found matching plugin twitch for URL twitch.tv/esl_csgo
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as username
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Starting player: 'C:\Program Files\VideoLAN\VLC\vlc.exe'
[cli][info] Got HTTP request from VLC/2.2.1 LibVLC/2.2.1
[cli][info] Opening stream: medium (hls)


It works fine on all my other computers which run 8.1 and 10 ? Any suggestions?
