### ISSUE TITLE
beam.pro plugin

### ISSUE THREAD

**Issue by dhasenan** [chrippa/livestreamer#771]
Beam.pro is a new game streaming site with low stream delay (3-5s rather than Twitch's 30s or more).

**Comment by Wolf480pl** [comment]
I was able to watch a beam.pro stream with VLC by manually extracting RTMP URL. I think it may be useful for developing a livestreamer plugin for beam.pro, (and also for people needing a temporary workaround) so here's how I did it:

I opened some beam.pro channel in Firefox, and looked at the developer console. There was a message like this: `"Connecting to Beam anycast RTMP network with smil file at: /api/v1/channels/6380/manifest.smil"` printed by some javascript. Looks like it uses an undocumented of beam.pro API, because `/api/v1/channels/:id/` is the official API url for a channel. (so instead of finding that link on the website, I guess you could ask API for a channel ID of a particular username).
I opened `https://beam.pro/api/v1/channels/6380/manifest.smil` and there was a small piece of XML with a `<meta base="rtmp://dist1.beam.pro/beam/"/>` tag in it's head, and what I guess is a list of video qualities in it's body. There was just one quality: `<video src="source_6380.mp4" title="source (800x500)" width="800" height="500"/>`. After appending `source_6380.mp4` from the video tag to the base URL from the meta tag, I got a link that I could succesfully open in VLC.

**Comment by wasche** [comment]
requesting `https://beam.pro/api/v1/channels/username/` and extracting `thumbnail.relid` looks like it gives you the active stream channel id, and if I put that into the url for `rtmp://dist1/beam.pro/beam/source_{relid}.mp4`, allows me to open it in vlc. But the manifest lists the various sizes. I saw a `source_` and a `480p_`. Thanks for the tip tho, this work around will work until a plugin is written.

**Comment by maop** [comment]
Just wanna thank you a lot for the info, i was able to play beam streams in MPC HC 1.7.8

Also +1 to the plugin request :P

**Comment by chrippa** [comment]
Implemented by #920.

**Comment by Wolf480pl** [comment]
Btw. I found out that the "replay of the last stream" feature of beam uses a manifest with URL like `http://dist.beam.pro/dash/:id/manifest.json` (where `:id` is user id, same as in live stream url). The `.photon` files mentioned in the manifest are in the same directory, and when `cat`-ed together, they make something that can be viewed with `ffplay` or `vlc`.

Wondering whether this could be implemented as VOD in livestreamer, and whether I should open another issue, or if this one should be reopened.
