### ISSUE TITLE
TV4 Play plugin no longer working

### ISSUE THREAD

**Issue by tboss** [chrippa/livestreamer#785]
Hey there,

I noticed today that the TV4 Play plugin is no longer working. Tried with a couple of (non-Premium) VODs,
<pre>
http://www.tv4play.se/program/badhotellet?video_id=3062402
http://www.tv4play.se/program/lets-dance?video_id=3086433
http://www.tv4play.se/program/%C3%A4ntligen-hemma?video_id=3030116
</pre>
and livestreamer (as usual) finds a matching plugin but immediately yields an error message such as the following

<code>
error: Unable to open URL: https://prima.tv4play.se/api/web/asset/3030116/play (hostname 'prima.tv4play.se' doesn't match 'vimondapi-stage.tv4play.se')
</code>

Setting the log level to debug (-l debug) didn't produce any more info.

I've verified that the VODs work in the browser (Chrome) so the service is definately up. Certainly, this error could of course be just a temporary issue, but I suppose more likely some sort of change to their streaming back-end that requires an update to the plugin.

/tboss

PS. Running Windows 7 64-bit and Livestreamer version 1.12.0.

**Comment by biezom** [comment]
pending the issue is resolved
you can use hlsvariant
*livestreamer "hlsvariant://http://tv4play-i.akamaihd.net/i/mp4root/2015-02-11/pid5185492(3062402_,T3MP4130,T3MP43,T3MP48,T3MP415,T3MP425,T3MP435,T3MP445,).mp4.csmil/master.m3u8" best -o Badhotellet-del-1.ts*
*livestreamer "hlsvariant://http://tv4play-i.akamaihd.net/i/mp4root/2015-03-13/did200001984_3086433_,T3MP4130,T3MP43,T3MP48,T3MP415,T3MP425,_.mp4.csmil/master.m3u8" best -o Let-s-dance-del-3.ts*
*livestreamer "hlsvariant://http://tv4play-i.akamaihd.net/i/mp4root/2014-12-15/pid5083635(3030116_,T3MP4130,T3MP43,T3MP48,T3MP415,T3MP425,).mp4.csmil/master.m3u8" best -o Antligen-hemma-del-13.ts*

**Comment by tboss** [comment]
Thanks for the tip, works well as a temporary work-around.

**Comment by biezom** [comment]
i not not use the easiest way
i use Tv4 app on android and i sniff the traffic to get the address of hls protocol
<pre> http://tv4play-i.akamaihd.net/i/<pre>
but there are easier
for the first example on a PC the site use hds protocol
<pre>http://tv4playhds-f.akamaihd.net/z/mp4root/2015-02-11/pid5185492(3062402_,T3MP4130,T3MP43,T3MP48,T3MP415,T3MP425,T3MP435,T3MP445,).mp4.csmil/manifest.f4m</pre>
so 
<pre>livestreamer  "hds://http://tv4playhds-f.akamaihd.net/z/mp4root/2015-02-11/pid5185492(3062402_,T3MP4130,T3MP43,T3MP48,T3MP415,T3MP425,T3MP435,T3MP445,).mp4.csmil/manifest.f4m?g=VNMWRPIOSDAS&hdcore=3.5.0" best -o Badhotellet-del-1.flv</pre>
