### ISSUE TITLE
Ustream.tv Plug-in No Longer Works

### ISSUE THREAD

**Issue by thackettx51v** [chrippa/livestreamer#799]
It seems like at 6:00 AM EST, ustream.tv may have updated their servers because livestreamer can no longer record any stream from ustream.tv.  I tried different channels on ustream.tv and tried both v1.11.1 and v1.12.0 on the Windows port of livestreamer without success.  I've tested this on two different Windows machines and on two different Internet connections.

The error is "error: No streams found on this URL: http://www.ustream.tv/channel/...."

**Comment by highflux7** [comment]
same problem linux v1.12.0

**Comment by dabada83** [comment]
the same on my machine with 1.12.0 :(

**Comment by trUSTssc** [comment]
_channel_id_re = re.compile("\"channelId\":(\d+)")

**Comment by liamkennedy** [comment]
I can confirm this too.   I use Livestreamer with my ISS-Above devices and users can no longer view the NASA HDEV video stream.   Verified no Ustream channel can be accessed.   

@trYSTssc - is that some kind of a workarund / fix?  If so... can you explain how to apply that?

**Comment by liamkennedy** [comment]
OK... probably obvious but I had to do a little "thinking" to work out where that change should go on my Pi.  

So I see it's in /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py  

then just replace the existing line which starts _channel_id_re = with the provided fix above.

And... that does seem to fix it.   

Thanks for showing what needs to be done.   

Will this be included in a quick update... or do I need to implement a work-around in the meantime?

I only have to get about 450 of my users to run the Livestreamer component update process - assuming 1.12.2 can be released right away.  Otherwise I'm likely going to have to get a little creative.

**Comment by biezom** [comment]
yes with this code 
_channel_id_re = re.compile("\"channelId\":(\d+)")
it works
thanks trUSTssc

**Comment by ChoRyuJin** [comment]
![2015-03-20_212122](https://cloud.githubusercontent.com/assets/10710953/6752341/99a98bce-cf48-11e4-9e22-fd05cadd8322.jpg)
I can still work with it in 18/03/2015 19:00 (HKT)
However, tonight, it doesn't work.

**Comment by dabada83** [comment]
livestreamer/src/livestreamer/plugins/ustreamtv.py at line 33

**Comment by ChoRyuJin** [comment]
What kind of tool should I use to edit it and build it?
I'm newbie to program. I'm sorry about that.

**Comment by skulblakka** [comment]
* Download the complete source code from GitHub
* Make your changes in /livestreamer/src/livestreamer/plugins/ustream.py
* Open CMD and move to /livestreamer or right click into the directory while holding shift and select "Open command prompt here"
* Enter "python setup.py install" and hit enter

**Comment by ChoRyuJin** [comment]
![2015-03-22_150551](https://cloud.githubusercontent.com/assets/10710953/6768421/5672234e-d0a5-11e4-80c6-74a56cc7e180.png)
![2015-03-22_150629](https://cloud.githubusercontent.com/assets/10710953/6768422/56b47ee2-d0a5-11e4-8294-7446794e8a35.png)
Thank you skulblakka! I could record things properly!
I noticed that If I enter command in cmd under windows, it is not necessary to enter "python"
I noticed that some other folders were also be created. What are those folders? Is it necessary?
