### ISSUE TITLE
Livestream plugin problem

### ISSUE THREAD

**Issue by saulofg** [chrippa/livestreamer#870]
Livestreamer 1.12.1 can't open livestream streams, it always return a error message, error: No streams found on this URL:, it has been return at least 2 weeks, before it was working perfectly, someone can help me?

**Comment by harrim4n** [comment]
Can confirm, plugin is broken for me as well.

**Comment by SirCmpwn** [comment]
Ditto.

**Comment by SirCmpwn** [comment]
ddevault@makase ~> livestreamer -l debug --player=mpv "http://livestream.com/spacex/events/3995038" best
    [cli][info] Found matching plugin oldlivestream for URL http://livestream.com/spacex/events/3995038
    error: No streams found on this URL: http://livestream.com/spacex/events/3995038

**Comment by chrippa** [comment]
Please try the latest [nightly](http://docs.livestreamer.io/install.html#nightly-build)/[git](http://docs.livestreamer.io/install.html#source-code) version.

**Comment by SirCmpwn** [comment]
WFM on git, thanks.

**Comment by harrim4n** [comment]
Same, thank you.

**Comment by saulofg** [comment]
Same too, thanks

**Comment by timb07** [comment]
I've just tried the git version (on Mac OS X) with "pip install -U git+https://github.com/chrippa/livestreamer.git", and it's not working for me, with the same issue:

    $ livestreamer -l debug http://livestream.com/accounts/3919156/events/4011517 best
    [cli][info] Found matching plugin livestream for URL http://livestream.com/accounts/3919156/events/4011517
    error: No streams found on this URL: http://livestream.com/accounts/3919156/events/4011517

It also fails with the command line given in the tutorial:
livestreamer twitch.tv/day9tv best

I haven't used livestreamer before, so can't tell if this is a regression or just something wrong with my installation/system. (And apologies if I'm just daft and this problem is answered elsewhere.)
